- name: apply nfd master
  command: "{{ kube_apply }} https://raw.githubusercontent.com/kubernetes-sigs/node-feature-discovery/v0.4.0/nfd-master.yaml.template"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  ignore_errors: true


- name: apply nfd worker
  command: "{{ kube_apply }} https://raw.githubusercontent.com/kubernetes-sigs/node-feature-discovery/v0.4.0/nfd-worker-daemonset.yaml.template"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  ignore_errors: true